# Generated by Django 3.2.8 on 2022-03-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',  
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
